### ISSUE TITLE
should read list of *.morbig files from stdin

### ISSUE THREAD

**Issue by treinen** [colis-anr/shstats#1]
shstats should just read the list of *.morbig files from stdin. This would simplify its use.

**Comment by Niols** [comment]
I agree, and am working precisely on that at the moment!

**Comment by Niols** [comment]
Fixed by 38f1d228e6ba82f9b7bc38a0783e8aee8ef3b9e0
There is also an option if one wants to have the old behaviour where the file list is in a file

shstats now reads the files from standard input. if they end up in ".morbig", it unserializes them. If not, it calls Morbig to parse them, which is still pretty fast
